project:
  type: website
  output-dir: docs
  
website:
  title: "Philippa Adolf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "#publications"
        text: Publications
      - href: "#talks"
        text: Talks
      - href: "#contact"
        text: Contact

format:
  html:
    theme: styles.scss
    toc: false