---
title: "Philippa Adolf"
subtitle: "Research assistant and doctoral candidate"
---

::: contact-info
{{< iconify hugeicons:university >}} [Department of Romance Linguistics,
University of Vienna](https://ucrisportal.univie.ac.at/de/persons/philippa-adolf) <br> {{< iconify entypo:address >}} Spitalgasse 2,
Hof 8 (Campus), 1090 Wien <br> {{< iconify ic:outline-email >}}
philippa.adolf\@uni.ac.at <br> {{< iconify simple-icons:osf >}}
[OSF](https://osf.io/wrq2a/) <br> {{< iconify mdi:github >}} GitHub <br>
{{< iconify mdi:linkedin >}} Linkedin <br>
{{< iconify academicons:researchgate-square >}} ResearchGate <br>
:::

## Research interests {#research-interests .section-title}

-   Synchronic and diachronic syntax of Iberoromance
-   Language Acquisition
-   Experimental and Corpus Linguistics
-   NLP and Machine Learning

## Publications {#publications .section-title}
::: content-container

::: publication-item
### Differential object marking in the L2 Spanish of L1 German speakers: A corpus-based analysis (2024)  
*In: Jonas Grünke, Andrea Pešková & Christoph Gabriel (eds.), Spanish as a second and third language: Approaching the linguistics-didactics interface, 39–69. Berlin: Frank & Timme GmbH.* [DOI: 10.57088/978-3-7329-8970-6_3](https://doi.org/10.57088/978-3-7329-8970-6_3)

::: {.abstract}
<details>
  <summary><strong>Abstract</strong></summary>
  <blockquote>
    El presente estudio contribuye a la investigación de la adquisición  
    del marcado diferencial de objeto (ingl. differential object marking,  
    DOM) del español como segunda lengua (L2), evaluando cuantitativamente  
    el uso escrito del DOM por hablantes nativos de español europeo y por  
    parte de hablantes de alemán como lengua primera (L1). Mediante un  
    enfoque basado en corpus, se analizan más de 100 textos escritos en  
    términos de la alternancia a/∅ con objetos directos nominales,  
    evaluando un conjunto de predictores semánticos y de estructura de la  
    información utilizando un análisis multifactorial basado en  
    clasificaciones de bosques aleatorios. Con este enfoque se investiga  
    hasta qué punto y en función de qué factores el grupo de hablantes L2  
    difiere del grupo nativo en su uso del DOM.
  </blockquote>
</details>

<details>
  <summary><strong>BibTeX Citation</strong></summary>

```bibtex
@incollection{adolfDifferentialObjectMarking2024,
    location = {Berlin},
    title = {Differential object marking in the L2 Spanish of L1 German speakers: A corpus-based analysis},
    isbn = {978-3-7329-8970-6},
    url = {https://doi.org/10.57088/978-3-7329-8970-6_3},
    pages = {39--69},
    booktitle = {Spanish as a second and third language: Approaching the linguistics-didactics interface},
    publisher = {Frank \& Timme {GmbH}},
    author = {Adolf, Philippa},
    editor = {Grünke, Jonas and Pešková, Andrea and Gabriel, Christoph},
    date = {2024},
    doi = {10.57088/978-3-7329-8970-6_3},
}
```
</details> 
:::

:::

:::
## Recent Talks {#talks .section-title}

::: content-container

::: talk-item
### Exploring Pronominal Variation in Iberoromance: experimental approaches to account for redundancy and deficiency *Coloquio lingüístico WS 2024/25*

:::

::: talk-item
### Statistics workshop *[https://doi.org/10.17605/OSF.IO/EJ46B](https://doi.org/10.17605/OSF.IO/EJ46B)*

Workshop on statistical methods for linguists with R.
:::

:::

## Ressources
::: content-container

::: publication-item
### Script for processing syllables
:::

::: publication-item
### Corpus of historical Portuguese
:::

:::

::: footer-content
This is a nice-looking footer.
:::
